name:                hashids-st
version:             0.1.0.0
github:              "githubuser/hashids-st"
license:             BSD3
author:              "Ben Levy"
maintainer:          "benjaminlevy007@gmail.com"
copyright:           "2020 Ben Levy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hashids-st#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- array

library:
  source-dirs: src

tests:
  hashids-st-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hashids-st
